### ISSUE TITLE
[bug]nuxt3 cant work

### ISSUE THREAD

**Issue by wintsa123** [huodoushigemi/wc-flow-layout#1]
nuxt3 cant run...

**Comment by huodoushigemi** [comment]
能看一下导入方式吗

**Comment by huodoushigemi** [comment]
Due to currently not supporting SSR, an error `HTMLElement is undefined` will be reported.

Change to the following import method

```diff
- import 'wc-waterfall'
+ if (typeof document != 'undefined') import('wc-waterfall')
```

https://stackblitz.com/edit/github-5wauea?file=nuxt.config.ts,app.vue
