### ISSUE TITLE
"wc-waterfall" has already been used with this registry

### ISSUE THREAD

**Issue by Rubinhuang9239** [huodoushigemi/wc-flow-layout#13]
感谢库主提供该库。

通过NPM使用在react项目中时偶现component重复定义
```
Failed to execute 'define' on 'CustomElementRegistry': the name "wc-waterfall" has already been used with this registry
```

https://github.com/huodoushigemi/wc-flow-layout/blob/c8fb3d3ab8038d4ad1a8e1d18b3c434fea1a9923/src/index.ts#L6C39-L6C55
建议改为
```ts
if (!customElements.get('wc-waterfall')) { customElements.define('wc-waterfall', WaterfallElement); }
```
需要的话可提PR。

**Comment by huodoushigemi** [comment]
👍

**Comment by Rubinhuang9239** [comment]
Thanks Buddy. It would be great if you don't mind to push the newest release to the NPM. :)
