### ISSUE TITLE
确实挺不错的，但能不能再加多个要求

### ISSUE THREAD

**Issue by wintsa123** [huodoushigemi/wc-flow-layout#2]
瀑布流的底部太丑了，不平整，能不能添加超过底部长度的卡片，然后用一个大盒子盖住最底层有数据的卡片的最底部，然后做一个虚化效果。就是有种镜面感觉，好像有很多没加载完一样的感觉

**Comment by huodoushigemi** [comment]
https://codepen.io/huodoushigemi/pen/BavoJwb?editors=1100

**Comment by wintsa123** [comment]
https://codepen.io/wintsa123/pen/oNJjagP?editors=1100
css没问题，但如何识别最低层需要添加多少个div呢？

**Comment by huodoushigemi** [comment]
https://codepen.io/huodoushigemi/pen/oNJjaQR

**Comment by wintsa123** [comment]
> https://codepen.io/huodoushigemi/pen/oNJjaQR
谢谢作者大大回复，我看了，很巧妙的方法，填了一个最小高度的盒子进去，以这个盒子计算。
但这样做有个bug：
1.作为瀑布流，左右盒子高度不明确，用这种方法，左右有数据的盒子会被盖住。不过作者的包确实很方便了，就是希望盒子移动的时候能加点动画就更好了

**Comment by huodoushigemi** [comment]
[Animation Demo](https://play.vuejs.org/#eNqFVE1zmzAQ/Ss75JCkDQb81ZQSz7SdHNpD22l75IJBBiUgaSRhk3r837sCm0CUj/HB2rdvdx+r1e6dz0JMtjVxQidSqaRCgyK6FquY0UpwqWEPkmzgABvJKzhH6nnvOt+l7i7RRG6SskQ4ZilnSkPKSwU3Ju5idnkC80QcscBHMPK6clgIDU0qUWImtKANDyGiTNQatm7FM1LexI6BYwf0gyBoyYTlBM0qadBa4MlbwX7f1T4cTJ5oLRE0J6z9TEJEX8oX+H6f0QgfJjylbZFhByBEap83NEp62a0M5Gd0u/KDyDP/Q2hqQzMbmtvQwoaWNvTBhq5t6KMFBb4N2eoDW31gqw9s9cFAfeQNe4lQ5A2mAk2lH0pzHLV8Be9gb8I1XqCimnIWgnFMZupTzPDaYnaWCNGRqkTm1BBqzdFrgMbd0UwXISyCqWhGIaisCxNJllGWh3CkAGw4066i/0gIU1K10JrLjEhXJhmtcXyXR+Y6Se9zyWuWuTgJXIZwdu2b39R/WixkunDTgpbZxZzBewgu8fEVhOaFxjK+jxkBA16iT4f0YPoWfTaiL96iz0dilic6PuP2Wpwrp1sKbpWIyZ3iDDdK27z46MBHEHbtNNjwEo0jdgqthQo9L80YxuMLpVs5YUR7TFSj0cCJUdqjLCPNhNINQXbsmLwo54A6tMKFs6H5ExUprwQtifwpzJCM1WBWvvveYlrW5OqEpwVJ75/B71TTif4liSJyi4uj92mcMaI79+2fH6TBc+/E1VOXyH7F+ZsoXtZGY0f7gqODsge8Vu23tqk4lX/VbaMJzv7xo4zQthstP3ZwY3995dMf5c4ms76Lh/+zWfXS)
