### ISSUE TITLE
在<wc-waterfall>上设置道具“gap”失败:值5无效。

### ISSUE THREAD

**Issue by Listen-to-poetry-in-the-wind** [huodoushigemi/wc-flow-layout#5]
Failed setting prop "gap" on <wc-waterfall>: value 5 is invalid. TypeError: Cannot read properties of undefined (reading 'relayout')
按照使用说明用的，，不知道为什么报警告。
![image](https://github.com/huodoushigemi/wc-flow-layout/assets/44539724/b2b62ded-3bad-41cc-9e50-fef34714d3f8)

![image](https://github.com/huodoushigemi/wc-flow-layout/assets/44539724/008e2b55-2eeb-4344-b73c-6dc66a5f55c4)

![image](https://github.com/huodoushigemi/wc-flow-layout/assets/44539724/eabd41ab-e056-4ada-8876-75212dc9a3ea)

![image](https://github.com/huodoushigemi/wc-flow-layout/assets/44539724/8f577b46-0b7a-441c-b5d7-8137ac6d78d8)

**Comment by Listen-to-poetry-in-the-wind** [comment]
设置gap是有效

**Comment by huodoushigemi** [comment]
v0.1.1 已修复
